apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rgaursmarthotelregistration 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rgaursmarthotelregistration 
    spec:
      containers:
        - name: rgaursmarthotelregistration 
          image: smarthotel1.azurecr.io/rgaursmarthotelregistration
          ports:
          - containerPort: 80